version: '2'

volumes:
  node_modules: {}

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagarme
      MYSQL_USER: pagarme
      MYSQL_PASSWORD: "p4g4rm3_db$$"

  base:
    build: .
    volumes:
      - .:/code
      - node_modules:/code/node_modules

  common:
    image: ${PROJECTPREFIX}_base
    environment:
      - NODE_ENV
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    external_links:
      - ${PROJECTPREFIX}_mysql_1

  web:
    extends: common
    command: node bin/server.js
    ports:
      - 5000:5000
  worker:
    extends: common
    command: node bin/worker.js


