#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "Tests started at..."
date "+%H:%M:%S"

# Export some common variables
export CI=true

# Pick 
if [ ! -z "$DRONE_BUILD_NUMBER" ]; then
	NOCONFLICT_CONTEXT=$DRONE_BUILD_NUMBER
elif [ ! -z "$BUILD_ID" ]; then
	NOCONFLICT_CONTEXT=$BUILD_ID
elif [ ! -z "$TRAVIS_BUILD_ID" ]; then
	NOCONFLICT_CONTEXT=$TRAVIS_BUILD_ID
else
	NOCONFLICT_CONTEXT=ci-$RANDOM
fi

echo "Running tests ..."
date "+%H:%M:%S"

exec script/test

